#   ===============> code by: ✪ 𝕊𝔸𝕃𝕄𝔸ℕ ✪ <=============== 
classes = {
    0: 'Speed Limit (20km/h)',
    1: 'Speed Limit (30km/h)',
    2: 'Speed Limit (50km/h)',
    3: 'Speed Limit (60km/h)',
    4: 'Speed Limit (70km/h)',
    5: 'Speed Limit (80km/h)', 
    6: 'End of Speed Limit (80km/h)',
    7: 'Speed Limit (100km/h)',
    8: 'Speed Limit (120km/h)',
    9: 'No Passing', 
    10: 'No Passing for HTVs',
    11: 'Crossroads Priority', 
    12: 'Priority Road',
    13: 'Yield', 
    14: 'Stop', 
    15: 'No-Vehicles',
    16: 'Vehicles Over 3.5 Tons Prohibited', 
    17: 'No Entry',
    18: 'General Caution', 
    19: 'Dangerous Curve Left',
    20: 'Dangerous Curve Right', 
    21: 'Double Curve',
    22: 'Bumpy Road', 
    23: 'Slippery Road',
    24: 'Road Narrows on the Right', 
    25: 'Road Work',
    26: 'Traffic Signals', 
    27: 'Pedestrians',
    28: 'Children Crossing', 
    29: 'Bicycles Crossing',
    30: 'Beware of Ice/Snow', 
    31: 'Animals Crossing',
    32: 'No Speed Limits',
    33: 'Turn Right Ahead',
    34: 'Turn Left Ahead', 
    35: 'Ahead Only',
    36: 'Go Straight or Right',
    37: 'Go Straight or Left',
    38: 'Keep Right',
    39: 'Keep Left',
    40: 'Roundabout',
    41: 'End of No Passing',
    42: 'End of No Passing Vehicles > 3.5 Tons',
    43: 'End of Priority Road',
    44: 'Railway Crossing with Gates',
    45: 'Railway Crossing without Gates',
    46: 'Two Way Traffic',
    47: 'Caution ! LandSliding',
    48: 'Caution ! Crosswinds',
    49: 'No Pedestrians',
    50: 'Weight Limit',
    51: 'Axle Weight Limit',
    52: 'Height Limit',
    53: 'Width Limit',
    54: 'No Right Turn',
    55: 'No Left Turn',
    56: 'No U-Turn',
    57: 'No Stopping/Clearway',
    58: 'No Waiting',
    59: 'Pedestrians Zone',
    60: 'Road Narrows on the Left',
    61: 'No Parking',
    62: 'U Turn Ahead',
    }
#   ===============> code by: ✪ 𝕊𝔸𝕃𝕄𝔸ℕ ✪ <=============== 