// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzNliV4tInBmDRWRfC-j65TvA4UGicqk',
    appId: '1:824516053496:web:cdda98b1730ed791e6ae0d',
    messagingSenderId: '824516053496',
    projectId: 'tsm-auth',
    authDomain: 'tsm-auth.firebaseapp.com',
    storageBucket: 'tsm-auth.appspot.com',
    measurementId: 'G-HQKC8YCCNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAby7KHh4vLp-lpvjka4oPce6TFkX8s-RM',
    appId: '1:824516053496:android:6f65617aab5f535fe6ae0d',
    messagingSenderId: '824516053496',
    projectId: 'tsm-auth',
    storageBucket: 'tsm-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCveob4NkKSTioTrBuzfICpdpPaS3ncFzM',
    appId: '1:824516053496:ios:406a6398dddeed72e6ae0d',
    messagingSenderId: '824516053496',
    projectId: 'tsm-auth',
    storageBucket: 'tsm-auth.appspot.com',
    iosBundleId: 'com.example.fypTrafficSignMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCveob4NkKSTioTrBuzfICpdpPaS3ncFzM',
    appId: '1:824516053496:ios:6a0e146bbc304037e6ae0d',
    messagingSenderId: '824516053496',
    projectId: 'tsm-auth',
    storageBucket: 'tsm-auth.appspot.com',
    iosBundleId: 'com.example.fypTrafficSignMaster.RunnerTests',
  );
}
